---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 9e38962c5685c4d21a54211fb638956c8b695d4d
    prometheus.io/port: "9779"
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/ms-currency
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    fabric8.io/scm-tag: HEAD
  labels:
    hystrix.enabled: "true"
    app: ola
    provider: fabric8
    version: 1.0.0
    group: com.redhat.ssi
  name: ms-currency
spec:
  ports:
  - name: 8001-tcp
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: ms-currency
    provider: fabric8
    group: com.redhat.ssi
