---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 9e38962c5685c4d21a54211fb638956c8b695d4d
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: master
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=ms-currency&var-version=1.0.0
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/ms-currency
  labels:
    hystrix.enabled: "true"
    app: ola
    provider: fabric8
    version: 1.0.0
    group: com.redhat.ssi
  name: ms-currency
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ms-currency
      provider: fabric8
      group: com.redhat.ssi
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 9e38962c5685c4d21a54211fb638956c8b695d4d
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=ms-currency&var-version=1.0.0
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/ms-currency
        fabric8.io/iconUrl: img/icons/spring-boot.svg
        fabric8.io/git-branch: master
        fabric8.io/scm-tag: HEAD
      labels:
        hystrix.enabled: "true"
        app: ola
        provider: fabric8
        version: 1.0.0
        group: com.redhat.ssi
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xmx256m
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ms-currency:1.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /deployments/config
          name: application-config
          readOnly: true
      volumes:
      - configMap:
          items:
          - key: application.yml
          name: currency-config
        name: application-config
